version: '3'
services:
  master:
    image: redis:3
    network_mode: "host"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /data/redis_master:/data
    command: redis-server --port 6380 --appendonly yes
  slave_1:
    image: redis:3
    network_mode: "host"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /data/redis_slave_1:/data
    command: redis-server --port 6381 --appendonly yes --slaveof 172.31.20.15 6380
  slave_2:
    image: redis:3
    network_mode: "host"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /data/redis_slave_2:/data
    command: redis-server --port 6382 --appendonly yes --slaveof 172.31.20.15 6380
  sentinel:
    build: sentinel
    ports:
      - "26379"
    environment:
      SENTINEL_DOWN_AFTER: 5000
      SENTINEL_FAILOVER: 5000
      MASTER_IP: 172.31.20.15
      MASTER_PORT: 6380
      TZ: Asia/Shanghai
    links:
      - master
      - slave_1
      - slave_2